"""
This program runs learner.py, a computational learner for cophonologies, a user-specified number of times.
The user must also input the command-line arguments for the learner.

This program sums the number of times that the learner produces a grammar, and prints out the grammars and their frequencies.
"""
import learner
import sys

n = int(sys.argv[5])

gdict = {}
for i in range(n):#Run the learner n times
	g, l = learner.main()
	if (str(g) not in gdict):#Add the grammar produced by the learner to the dictionary
		gdict[str(g)] = 1
	else:#Update the grammar's frequency count
		oldc = gdict[str(g)]
		gdict[str(g)] = oldc+1
for i in gdict.keys():#Print all grammars generated by the learner and their frequencies
	print "key: " + i
	print gdict[i]